### ISSUE TITLE
Error in displaying the date of statistics

### ISSUE THREAD

**Issue by SciCrea** [modmore/BigBrother#32] opened 2019-09-28 08:23 UTC
Thanks for the nice and helpful addon!
The only problem is it's not the right date in the statistics. For example, if today is September 28, the statistics will be written on September 27, but the statistics of September 28. Simply put, shows yesterday's date, and today's statistics

**Comment by Mark-H** [comment] 2019-11-26 18:00
Duplicate of #12

**Closed by Mark-H** 2019-11-26 18:00 UTC
