### ISSUE TITLE
Its not possible to assign Analytics accounts to MODX user accounts any longer

### ISSUE THREAD

**Issue by gadgetto** [modmore/BigBrother#1] opened 2015-05-20 14:30 UTC
![screenshot](https://cloud.githubusercontent.com/assets/876737/7728089/66b15c98-ff0d-11e4-8af4-bba1ecf06fa8.png)

BigBrother settings aren't saved to user settings.

**Comment by Mark-H** [comment] 2015-05-20 14:52
Hmm this is working as expected for me. Do you see any errors in the console/network, or the MODX error log when making a change?

![screen shot 2015-05-20 at 16 51 23](https://cloud.githubusercontent.com/assets/312944/7728603/7c90dbf8-ff10-11e4-87e7-e983dac5bb89.png)

![screen shot 2015-05-20 at 16 51 05](https://cloud.githubusercontent.com/assets/312944/7728588/7134f74e-ff10-11e4-9011-427f7d8a45ad.png)

**Comment by gadgetto** [comment] 2015-05-20 15:43
Just retried this on a site with only a few users - and here it works like expected.
The other site has over 3000 users and there I can't assign an Analytics account to a specific user.
If I click on the grid dropdown the list of Analytics accounts is fetched - but If I choose an account the dropdown closes and the Analytics id is shown for about 1 second and the jumps back to "default".

No corresponding entry in the MODX error log.

Could this be a JS timing problem?

**Comment by Mark-H** [comment] 2015-05-20 18:53
I've managed to reproduce and figured out why it's happening too - looks like there's a bit of a logic flaw in the assignaccount processor, will get that fixed in a few.

**Comment by Mark-H** [comment] 2015-05-20 18:53
(Basically, if a user has settings assigned to it already, it doesn't create the new bigbrother setting, it only updates them if they already exist)

**Comment by Mark-H** [comment] 2015-05-20 19:16
Fixed in https://github.com/modmore/BigBrother/commit/c9cc4c373beb289b7500f37d4989a62595f84250

**Closed by Mark-H** 2015-05-20 19:16 UTC
